### ISSUE TITLE
Error compiling the hdt-jni

### ISSUE THREAD

**Issue by dachafra** [anifledramos/tfm-rdf#1]
```
ctory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testDictionary(org.rdfhdt.hdtjena.solver.OptimizedCountTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rdfhdt.hdt.dictionary.impl.section.JNIDictionarySection
	at org.rdfhdt.hdt.dictionary.impl.JNIDictionary.<init>(JNIDictionary.java:34)
	at org.rdfhdt.hdt.dictionary.DictionaryFactory.createDictionary(DictionaryFactory.java:82)
	at org.rdfhdt.hdt.hdt.impl.HDTImpl.createComponents(HDTImpl.java:90)
	at org.rdfhdt.hdt.hdt.impl.HDTImpl.<init>(HDTImpl.java:132)
	at org.rdfhdt.hdt.hdt.HDTManagerImpl.doGenerateHDT(HDTManagerImpl.java:133)
	at org.rdfhdt.hdt.hdt.HDTManager.generateHDT(HDTManager.java:142)
	at org.rdfhdt.hdtjena.solver.OptimizedCountTest.setUp(OptimizedCountTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error:
  testTriplePattern(org.rdfhdt.hdtjena.solver.OptimizedCountTest): no jnidictionary in java.library.path
  testGraph(org.rdfhdt.hdtjena.solver.OptimizedCountTest): Could not initialize class org.rdfhdt.hdt.dictionary.impl.section.JNIDictionarySection
  testWrong(org.rdfhdt.hdtjena.solver.OptimizedCountTest): Could not initialize class org.rdfhdt.hdt.dictionary.impl.section.JNIDictionarySection
  testAllTriples(org.rdfhdt.hdtjena.solver.OptimizedCountTest): Could not initialize class org.rdfhdt.hdt.dictionary.impl.section.JNIDictionarySection
  testDictionary(org.rdfhdt.hdtjena.solver.OptimizedCountTest): Could not initialize class org.rdfhdt.hdt.dictionary.impl.section.JNIDictionarySection

Tests run: 8, Failures: 0, Errors: 5, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for RDF/HDT 2.0:
[INFO]
[INFO] RDF/HDT ............................................ SUCCESS [  0.383 s]
[INFO] HDT API ............................................ SUCCESS [  1.335 s]
[INFO] HDT Java Core ...................................... SUCCESS [  7.912 s]
[INFO] HDT Jena ........................................... FAILURE [  2.639 s]
[INFO] HDT Java Command line Tools ........................ SKIPPED
[INFO] HDT Java Package ................................... SKIPPED
[INFO] HDT Fuseki ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.425 s
[INFO] Finished at: 2021-06-09T14:10:44+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project hdt-jena: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/dchaves/Documents/proyectos/tfms/tfm-rdf/hdt-jni/hdt-jena/target/surefire-reports for the individual test results.
```

I just cloned the repo and follow the instructions from the README

**Comment by anifledramos** [comment]
Was it when performing `mvn install` ? Try with the flag -DskipTests using the command `mvn -DskipTests install`, the current tests are configured to work with the original HDT implementation and their adaptation is future work, I forgot to add that in the README but it is already configured in the Dockerfile if you want to run it automatically.

**Comment by dachafra** [comment]
thanks! It's solved skipping the tests, please include it in the README

**Comment by anifledramos** [comment]
Already done that, thanks for letting me know! I will close this issue
